apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: quarkus-build-run-
spec:
  pipelineRef:
    name: quarkus-build
  podTemplate:
    securityContext:
      fsGroup: 65532
  params:
    - name: repo-url
      value: https://github.com/myfear/quarkus-tekton-test.git
    - name: revision
      value: main
    - name: image
      value: registry.kube-system.svc.cluster.local:80/pipeline-demo:latest
  workspaces:
    - name: shared-source
      persistentVolumeClaim:
        claimName: pipeline-source-pvc